# Generated by Django 6.0.4 on 2026-04-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_restore_feature_chat_without_django_llm_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCodebaseAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codebase_agent_config', to='projects.project')),
            ],
        ),
    ]
